Resources:
  createUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'createUserRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CreateUserPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userTable}'
  followUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'followUserRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FollowUserPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userFollowingTable}'
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userTable}'
  unfollowUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'unfollowUserRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: UnfollowUserPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userFollowingTable}'
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userTable}'
  getFollowedUsersListRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'getFollowedUsersListRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetFollowedUsersListPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'dynamodb:Query'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userTable}'
              - Effect: Allow
                Action:
                  - 'dynamodb:Query'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userFollowingTable}'
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userTable}'
  createPostRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'createPostRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CreatePostPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.postTable}'
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userTable}'
  deletePostRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'deletePostRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DeletePostPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.postTable}'
  getFollowedUserPostsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'getFollowedUserPostsRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GetFollowedUserPostsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - 'dynamodb:Query'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.postTable}'
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userTable}'
              - Effect: Allow
                Action:
                  - 'dynamodb:Query'
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.dynamodb.userFollowingTable}'